services:
  ###############################################################
  # Backend
  ###############################################################
  schedule-app:
    image: schedule-app
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    command: pnpm run dev
    volumes:
      - ./src:/var/app/src
    ports:
      - 3000:3000
    env_file:
      - .env
    links:
      - schedule-db
      - schedule-redis
  ###############################################################
  # Database
  ###############################################################
  schedule-db:
    container_name: schedule-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: schedule-db
      POSTGRES_USER: schedule-db
      POSTGRES_DB: schedule-db
    ports:
      - 5432:5432
    volumes:
      - postgres-schedule-db:/var/lib/postgresql/data
    restart: unless-stopped
  ###############################################################
  # Redis
  ###############################################################
  schedule-redis:
    container_name: schedule-redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-internal:/data
    restart: unless-stopped
volumes:
  postgres-schedule-db:
  redis-internal:
